version: 2.1

jobs:
  build:
    working_directory: ~/codeclimate/codeclimate-sonar-java
    steps:
      - checkout
      - run:
          name: Build
          command: make image
      - run:
          name: Test
          command: make test
